# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  repositories:
    - repository: templates
      type: git
      name: Demo/templates

pool:
  vmImage: ubuntu-latest

steps:
- template: dotnet.yml@templates