# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  repositories:
    - repository: templates
      type: git
      name: Demo/templates

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs: 
    - job: 'api_build'
      steps:
      - template: dotnet.yml@templates
  
  - stage: DeployDev
    jobs:
    - deployment: 'deploy_dev'
      environment: 
        name: dev
        resourceType: VirtualMachine
        tags: demo
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CopyFiles@2
              inputs:
                SourceFolder: '$(Pipeline.Workspace)/drop'
                Contents: '**'
                TargetFolder: 'd:\temp'
            - task: CmdLine@2
              inputs:
                script: |
                  echo Write your commands here
                  
                  echo Hello world

