# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  repositories:
    - repository: templates
      type: git
      name: Demo/templates

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs: 
    - job: 'api_build'
      steps:
      - template: dotnet.yml@templates
  
  - stage: DeployDev
    jobs:
    - deployment: 'deploy_dev'
      environment: 
        name: dev
        resourceType: VirtualMachine
        tags: demo
      strategy:
        runOnce:
          deploy:
            steps:
            - task: CopyFiles@2
              inputs:
                SourceFolder: '$(Pipeline.Workspace)/drop/s'
                Contents: '**'
                TargetFolder: 'd:\webapp'
            
            - task: IISWebAppManagementOnMachineGroup@0
              inputs:
                EnableIIS: true
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'CreateOrUpdateWebsite'
                WebsiteName: 'DemoApp'
                WebsitePhysicalPath: 'd:\webapp'
                WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                AddBinding: true
                Bindings: |
                  {
                              bindings:[
                                  {
                                      "protocol":"http",
                                      "ipAddress":"*",
                                      "hostname":"*",
                                      "port":"80",
                                      "sslThumbprint":"",
                                      "sniFlag":false
                                  }
                              ]
